### ISSUE TITLE
Barcode scanning crashes on first use after permission popup

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/CoCeMoCl#12]
Barcode scanner for QR code cannot be used when the camera permission was granted right before. App needs to be killed, until the QR scanning works again.

**Comment by danielsteiner** [comment]
https://github.com/Redth/ZXing.Net.Mobile/issues/741#issuecomment-406638487

That workaround could fix this bug. I will take a look at this later today / tomorrow.

**Comment by robo-w** [comment]
fixed for android. if it is a problem in iOS too, please reopen.
