### ISSUE TITLE
Show useful position information in app

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/CoCeMoCl#2]
Currently the raw data of the position is displayed in the app. This should show useful information for the user, for example:
* When was the last valid position requested
* Accuracy of the last queried position

**Comment by danielsteiner** [comment]
Can be realised with [Geolocation.GetLastKnownLocationAsync](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.geolocation.getlastknownlocationasync?view=xamarin-essentials-android#Xamarin_Essentials_Geolocation_GetLastKnownLocationAsync)

**Comment by heinrichmartin** [comment]
Are we talking about `Über / Einstellungen` > `Aktueller Standort`? This shows no data in my app, just the captions `Latitude`, ...

**Comment by fs1** [comment]
> Are we talking about `Über / Einstellungen` > `Aktueller Standort`? This shows no data in my app, just the captions `Latitude`, ...

The captions will be substituted with your position data, as soon as your phone knows its position.

**Comment by robo-w** [comment]
fixed in version 1.1.2
