### ISSUE TITLE
Incident update loads forever

### ISSUE THREAD

**Issue by heinrichmartin** [wrk-fmd/CoCeMoCl#24]
GIVEN the incidents' view is open
WHEN I drag down the list
THEN a loading indicator appears and never goes away

Is dragging down implemented? Does it trigger a scope request?

**Comment by fs1** [comment]
I can reproduce this issue with my Samsung Galaxy XCover 3 (SM-G389F) and GeoClient 1.1.0.

**Comment by robo-w** [comment]
will be fixed in >1.1.1

**Comment by fs1** [comment]
works for me now (GeoClient 1.1.1)
