### ISSUE TITLE
Incident page is cut off

### ISSUE THREAD

**Issue by heinrichmartin** [wrk-fmd/CoCeMoCl#25]
On the incident page, no scroll bar is available. Some information is not shown on the screen.

**Comment by danielsteiner** [comment]
Can you provide a screenshot and some information about your Phone? It looks good on my OnePlus 5

**Comment by heinrichmartin** [comment]
Screenshot sent per email. Guess my screen in smaller. Android 6.0.1.

**Comment by fs1** [comment]
I have the same issue here: Samsung Galaxy XCover 3 (SM-G389F) with 6.0.1

**Comment by danielsteiner** [comment]
Will Take a look at this this evening - I am just not sure how to replicate this bug as it looks as it should on my test devices (OnePlus 5 / Samsung Galaxy S5 Mini)

**Comment by heinrichmartin** [comment]
> I am just not sure how to replicate this bug as it looks as it should on my test devices

Is your device showing a scroll bar? Try to add more units?

**Comment by fs1** [comment]
> I am just not sure how to replicate this bug as it looks as it should on my test devices
Just rotate the device/screen, if the incident is "long" enough you can probably reproduce it.

**Comment by heinrichmartin** [comment]
> Just rotate the device/screen, if the incident is "long" enough you can probably reproduce it.

Smart. If I do so, the botton to the map is gone...

**Comment by danielsteiner** [comment]
Okay, i found out why this happens - Units marked as "Führungskraft" see all units and the list was too long. 
I've wrapped the List in a ScrollView so that it is scrollable. Should be fixed now.

**Comment by robo-w** [comment]
@danielsteiner : according to https://forums.xamarin.com/discussion/2857/listview-inside-scrollview/p1 a listview never should be inside of a scrollview. Details for possible fixes see in slack.
