### ISSUE TITLE
App crashes on revoking location permission

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/CoCeMoCl#31]
Version 1.1.1
Android 6.0.1
originally reported in #30 by @heinrichmartin 

GIVEN the app is closed
WHEN I retract the app's permission to the location data in the mobile's settings
THEN the app crashes
AND it crashes twice (two notifications from Android)

**Comment by robo-w** [comment]
Cause:
On revoking the location permission, android restarts the service running in the background. On restart, it is started directly by android, and not via the MainActivity, where the location permission is checked. Therefore the whole app crashes.

Revoking the permission is blocking the main feature of the app. I think its fine to keep it this way, and show the user that the app cannot operate properly.

**Comment by heinrichmartin** [comment]
Revoking the location permission was just a work around #32. Force stopping the app is another option that works fine.
