### ISSUE TITLE
Change refresh button while incidents are loading

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/CoCeMoCl#38]
Change the appearance of the refresh button in the incident list view, if the incidents are currently refreshing. (grey it out, use slightly different icon, ...)

**Comment by danielsteiner** [comment]
A spinning icon should be enough in my opinion. On the other hand, I am not even sure if we really need the refresh button - the pull to refresh gesture is commonly known to do exactly this.

**Comment by heinrichmartin** [comment]
My 2 cents:
If the list auto-refreshes, then remove the button. Keep the pull gesture.
Otherwise, keep the button, too, as a hint that a refresh is possible.

**Comment by robo-w** [comment]
the manual refresh via the button did not update the IsBusy property. By doing so, the loading icon of the list is automatically shown.
