### ISSUE TITLE
Show list of current incidents

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/CoCeMoCl#4]
On the first page the result of the "scope" response shall be shown. In the first approach, the incident data of the own unit shall be parsed and be shown on the first page.

Per incident an own list item shall be shown.

**Comment by danielsteiner** [comment]
Incidents are now displayed after the first manual refresh or when swiping back to the incident list page (first page). They are alsow fetched on app start but the response takes too long for the task to finish.
