### ISSUE TITLE
change url for about/information data

### ISSUE THREAD

**Issue by fs1** [wrk-fmd/CoCeMoCl#48]
Currently (v1.1.3) there is a link to the old information page in the redcross intranet on the _Einstellungen_ page. Please update this link to the new information page which contains also information about the app. Furthermore I suggest to not link it directly, instead link it to a page on e.g. geo.fmd.wrk.at where a HTTP status code 307 containing the correct location is returned. This way you can easily change the url without having to change the code of the app.

**Comment by robo-w** [comment]
Changed:
* URL references /about.html on the server of the read QR code (no server stored in code)
* about.html redirects to intranet page
