### ISSUE TITLE
Provide button for navigation

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/CoCeMoCl#6]
Provide a button with the navigation to the next target of the incident.

Relies on #4. Per incident the button shall depend on the state of the own unit:
* If the unit is in Assigned or ZBO, the button shall generate a link to BO. Any later state shall generate a link to AO (if present).

Implementation Note: Only the coordinates shall be provided to the navigation link. No address data shall be sent to the maps app.

**Comment by danielsteiner** [comment]
Functionalit added with the latest commits to branch bugfix/#4-show-list-of-current-incidents - parsing coordinates is still flawed but will be fixed within the next few days.

**Comment by fs1** [comment]
I opened the incident in the app and I am in state ZAO, but there is still a button "view BO on map", which shows the BO. Instead I expected either an additional button or a renamed button to "view AO on map" which shows me the AO on the map.

**Comment by danielsteiner** [comment]
If I am not mistaken, we only get the coordinates of the BO from Geobroker, not the AO.

**Comment by heinrichmartin** [comment]
Maybe this is not implemented in CoCeSo, but when a unit is ZAO, its `lastPoint` should be the BO and its `targetPoint` should be the AO iirc ...

**Comment by danielsteiner** [comment]
I just inspected the GeoClient - targetPoint is the current target - it has the coordinates of the BO when you are ZBO / BO and of the AO when you are ZAO / AO. Should be implemented soon.

**Comment by robo-w** [comment]
Discussion outcome:
* geobroker was not built to support the AO
* In the app was only the "BO" part implemented so far
* In fact there is no "next location" for the incident. On unit level we could show the next target, but the view is right now built incident-based

Fix of the implementation:
* Geobroker will be extended with an additional field of the destination
* There will be two buttons (next to each other in the same row?). Each button is enable, iff coordinates for the resp. point are available
  * Example Relocation: Only AO is active
  * Example Task: Only BO is active, if no AO is entered yet, or the AO cannot be resolved
